export function createInteractiveDocumentDemo() {
  return [
    '<prompt_template name="identity" role="system">',
    "# {{ <@local:profile>.name }}",
    "",
    "你是一名{{ <@local:profile>.role }}，表达方式应保持{{ <@local:profile>.tone }}。",
    "",
    "## 调查重点",
    "",
    "{{ <@local:topics> }}",
    "</prompt_template>",
    "",
    "<data>",
    '  <sub_data name="profile">',
    "    <enable_updater>",
    "      true",
    "    </enable_updater>",
    "    <description>",
    "      角色的基本结构。",
    "    </description>",
    '    <content type="json">',
    "      {",
    '        "name": "星野",',
    '        "role": "异常事件调查员",',
    '        "tone": "克制、敏锐"',
    "      }",
    "    </content>",
    "    <wrapper>",
    "      function (value, variable) {",
    "        return {",
    "          get name() { return variable.value.name; },",
    "          get role() { return variable.value.role; },",
    "          get tone() { return variable.value.tone; },",
    "          setTone(tone) { variable.value.tone = String(tone); return variable.value.tone; },",
    "        };",
    "      }",
    "    </wrapper>",
    "  </sub_data>",
    '  <sub_data name="topics">',
    "    <enable_updater>",
    "      false",
    "    </enable_updater>",
    "    <description>",
    "      当前角色应优先关注的主题。",
    "    </description>",
    '    <content type="json">',
    '      ["现场线索", "证词矛盾", "未解释的时间差"]',
    "    </content>",
    "    <wrapper>",
    "    </wrapper>",
    "  </sub_data>",
    "</data>",
    "",
    "<memory>",
    "  <compression_threshold>",
    "    24",
    "  </compression_threshold>",
    "</memory>",
  ].join("\n");
}
