import type { ModelProviderDefinition } from "../domain/model-provider";
import { providerIconUrl } from "./provider-icons";

export const builtinModelProviders: ModelProviderDefinition[] = [
  {
    id: "openai",
    name: "OpenAI",
    description: "OpenAI 官方接口，适合通用对话、视觉和语音模型。",
    icon: "openai",
    iconUrl: providerIconUrl("openai"),
    baseUrl: "https://api.openai.com/v1",
    apiKeyName: "openai_API_KEY",
    enabled: true,
    builtIn: true,
    runtime: "remote",
    models: [
      {
        id: "gpt-4o",
        name: "GPT-4o",
        apiType: "chat",
        contextSize: 128000,
        enabled: true,
      },
      {
        id: "gpt-4o-mini",
        name: "GPT-4o mini",
        apiType: "chat",
        contextSize: 128000,
        enabled: true,
      },
      {
        id: "text-embedding-3-small",
        name: "Text Embedding 3 Small",
        apiType: "embedding",
        enabled: true,
      },
      {
        id: "gpt-image-2",
        name: "GPT Image 2",
        apiType: "image",
        enabled: false,
      },
      {
        id: "gpt-4o-mini-tts",
        name: "GPT-4o mini TTS",
        apiType: "tts",
        enabled: false,
      },
      {
        id: "whisper-1",
        name: "Whisper",
        apiType: "asr",
        enabled: false,
      },
    ],
  },
  {
    id: "huggingface",
    name: "Hugging Face",
    description: "Inference Providers 多模型平台；仅显式登记可生成图片的模型。",
    icon: "huggingface",
    iconUrl: providerIconUrl("huggingface"),
    baseUrl: "https://router.huggingface.co",
    apiKeyName: "huggingface_API_KEY",
    enabled: false,
    builtIn: true,
    runtime: "remote",
    models: [
      { id: "black-forest-labs/FLUX.1-dev", name: "FLUX.1 dev", apiType: "image", enabled: true },
      { id: "black-forest-labs/FLUX.1-schnell", name: "FLUX.1 schnell", apiType: "image", enabled: true },
      { id: "stabilityai/stable-diffusion-xl-base-1.0", name: "Stable Diffusion XL Base 1.0", apiType: "image", enabled: true },
    ],
  },
  {
    id: "deepseek",
    name: "DeepSeek",
    description: "DeepSeek 官方接口，适合对话和推理模型。",
    icon: "deepseek",
    iconUrl: providerIconUrl("deepseek"),
    baseUrl: "https://api.deepseek.com",
    apiKeyName: "deepseek_API_KEY",
    enabled: false,
    builtIn: true,
    runtime: "remote",
    models: [
      {
        id: "deepseek-v4-flash",
        name: "DeepSeek V4 Flash",
        apiType: "chat",
        contextSize: 64000,
        enabled: true,
      },
      {
        id: "deepseek-v4-pro",
        name: "DeepSeek V4 Pro",
        apiType: "chat",
        contextSize: 64000,
        enabled: true,
      },
    ],
  },
];
