export const contextDocumentFormatPrompt = [
  "## Context Markdown 与数据资源",
  "上下文入口是插件根目录的 `context.md`。它是普通 Markdown，数据定义不内嵌在正文中。",
  "普通内容编译为 system 消息；需要明确角色时使用以下不可嵌套的块：",
  "```md",
  ":::pulsar role=system",
  "系统内容",
  ":::",
  "",
  ":::pulsar role=user",
  "示例用户消息",
  ":::",
  "```",
  "角色只能是 system、user 或 assistant。普通 Markdown 代码围栏中的标记不会被解析。",
  "可复用状态存放在独立 `.data` 文件中；通过 `imports.resource(path)` 或 `imports.resourceById(id)` 导入时返回水合后的只读 JS facade。",
  "`.data` 自己声明 `isolation: 'resource' | 'conversation'`，引用方不能覆盖隔离级别。",
  "绑定后的值通过 `data.<alias>`（以及大写别名 `DATA.<alias>`）用于 `{{ }}` 与 `[[ ]]` 表达式。",
  "外部文档、容器与配置统一通过宏内的 `imports` 函数访问，依赖参数必须使用字符串字面量。",
  "最终上下文从 `context.md` 开始沿显式引用图编译；未被引用的文件不会自动进入上下文。",
].join("\n");
