import { createApp } from "vue";
import { createPinia } from "pinia";
import { createNotivue } from "notivue";
import App from "./App.vue";
import { useBackupStore } from "@/features/Backup/application/backup-store";
import "@/features/Agent/presentation/register-agent-generation-components";
import "@/features/Resources/Conversation/presentation/register-conversation-workspace";
import "@/features/Notification/presentation/register-notification-workspace";
import "@/features/Resources/InteractiveDoc/presentation/register-interactive-document-workspace";
import "@/features/Resources/Plugin/presentation/register-plugin-workspace";
import "@/features/UI/schedule/presentation/register-schedule-workspace";
import "./styles/globals.css";
import "@milkdown/crepe/theme/common/style.css";
import "@milkdown/crepe/theme/frame.css";
import "@milkdown/kit/prose/tables/style/tables.css";
import "@milkdown/kit/prose/view/style/prosemirror.css";
import "notivue/notification.css";
import "notivue/animations.css";

const app = createApp(App);
const pinia = createPinia();
app.use(pinia).use(createNotivue()).mount("#app");
void useBackupStore(pinia).initialize();
